# Generated by Django 5.1.1 on 2024-10-15 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appinstabill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha_facturacion',
            field=models.CharField(max_length=256),
        ),
    ]
