# Generated by Django 5.1.1 on 2024-10-15 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appinstabill', '0002_alter_factura_fecha_facturacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='factura',
            field=models.ForeignKey(db_column='id_factura', on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='appinstabill.factura'),
        ),
    ]
