# Generated by Django 5.1.1 on 2024-10-16 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appinstabill', '0003_alter_producto_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='appinstabill.cliente'),
        ),
    ]
